import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
const Header: NextPage = () => {
  const [menus, setMenus] = useState([
    {label: 'Home', active: true, url: '/'},
    {label: 'User Profile', active: false, url: '/#our-service'},
    {label: 'Dashboard', active: false, url: '/dashboard'}
  ])
  const handleChangeMenu = (i:any) => {
    var newMenus = menus
    for (let dd in newMenus) {
       if (parseInt(dd) !== i) {
          newMenus[dd].active = false
       } else {
          newMenus[i.toString()].active = true
       }
    }
    setMenus(newMenus)
  }
  // useEffect(() => {
  //   window.addEventListener('scroll', _ => {handleScroll(_)})
  // })
  // const handleScroll = (event: any) => {
  //  var newMenus = menus
  //  var x = 0
  //  var y = window.pageYOffset
  //  if (y >= 400) {
  //     x = 1
  //  }
  //  for (let dd in newMenus) {
  //     if (parseInt(dd) !== x) {
  //        newMenus[dd].active = false
  //     } else {
  //        newMenus[x].active = true
  //     }
  //  }
  //  // console.log(x)
  //  // console.log(y)
  //  setMenus(newMenus)
  // }
  return (
    <div>
      <Head>
        <title>My Invitation</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <section className='nav-top'>
        <div className='list-menu'>
          <ul>
          {
              menus.map((val, index) => {
                return (
                 <li className={((val.active) ? 'active' : '')} key={index}><Link href={val.url} key={index} scroll={true}><a onClick={_ => {handleChangeMenu(index)}} >{val.label} </a></Link></li>
                )
              })
           }
          </ul>
        </div>
      </section>
    </div>
  )
}

export default Header
